installation_path:
  description: "Installation path:"
  type: string
  value: ""
# ruleset:
#   description: "Ruleset."
#   type: select
#   options:
#     default: "Default"
#     all: "All"
#     none: "None"
#   value: "default"
# verible_lint_args:
#   description: "Extra command line arguments passed to the Verible tool."
#   type: array
#   value: []
# rules:
#   description: "What rules to use. Prefix a rule name with “-” to disable it."
#   type: array
#   value: []
