<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>tcl</string>
    <key>scopeName</key>
    <string>source.tcl</string>
    <key>fileTypes</key>
    <array>
      <string>tcl</string>
      <string>xdc</string>
      <string>sdc</string>
    </array>
    <key>uuid</key>
    <string>45aff42e-4fcd-4717-829b-4cdaf9d707aa</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#command</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.tcl</string>
            <key>match</key>
            <string>\s*\#.*</string>
          </dict>
        </array>
      </dict>
      <key>command</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tcl_commands</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#default_command</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#brackets</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.tcl</string>
            <key>match</key>
            <string>(?:0(?:x|o|b))?\d+(?!\.)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.tcl</string>
            <key>match</key>
            <string>\d+\.(?:\d+(?:[eE][+-]?\d+)?)?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.tcl</string>
            <key>match</key>
            <string>(?:\+|\-|\~|\!|\*\*|\*|\%|\&lt;\&lt;|\&gt;\&gt;|\&lt;\=|\&gt;\=|\&lt;|\&gt;|\=\=|\!\=|eq|ne|in|ni|\&amp;\&amp;|\&amp;|\|\||\||\^|\?|\:)</string>
          </dict>
        </array>
      </dict>
      <key>double_quotes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.tcl</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\$(?:(?:\:\:)?[a-zA-Z0-9_]+)+)\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#brackets</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.tcl</string>
            <key>match</key>
            <string>\$(?:(?:\:\:)?[a-zA-Z0-9_]+)+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.tcl</string>
            <key>begin</key>
            <string>\$\{</string>
            <key>end</key>
            <string>\}</string>
          </dict>
        </array>
      </dict>
      <key>braces</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.word.generic.tcl</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#braces</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tcl_braces</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.word.tcl.tcl</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#command</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expr_braces</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.word.expr.tcl</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#command</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>proc</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.proc.tcl</string>
            <key>begin</key>
            <string>\b(proc)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;=proc)(?:\s+|\\)</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.tcl</string>
                    <key>match</key>
                    <string>[^\"\$\[\s]+</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#braces</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#brackets</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#double_quotes</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#brackets</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#tcl_braces</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>for</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.for.tcl</string>
            <key>begin</key>
            <string>\b(for)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.for.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?:\s+|\\)</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#tcl_braces</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#brackets</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#expr_braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#double_quotes</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#brackets</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#tcl_braces</string>
                          </dict>
                          <dict>
                            <key>begin</key>
                            <string>(?:\s+|\\)</string>
                            <key>end</key>
                            <string>(?:(;)|(?=\})|(?=\])|$)</string>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>include</key>
                                <string>#double_quotes</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#brackets</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#tcl_braces</string>
                              </dict>
                            </array>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>foreach</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.foreach.tcl</string>
            <key>begin</key>
            <string>\b(foreach)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.foreach.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?:\s+|\\)</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.tcl</string>
                    <key>match</key>
                    <string>\S+</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#braces</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#variable</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#brackets</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#double_quotes</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#brackets</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#tcl_braces</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>if</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.if.tcl</string>
            <key>begin</key>
            <string>\b(if)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.if.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?:\s+|\\)</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#expr_braces</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.end.semicolon.tcl</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#brackets</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#tcl_braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>endCaptures</key>
                        <dict>
                          <key>1</key>
                          <dict>
                            <key>name</key>
                            <string>punctuation.end.semicolon.tcl</string>
                          </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>begin</key>
                            <string>\b(else)\b</string>
                            <key>beginCaptures</key>
                            <dict>
                              <key>1</key>
                              <dict>
                                <key>name</key>
                                <string>keyword.control.else.tcl</string>
                              </dict>
                            </dict>
                            <key>end</key>
                            <string>(?:(;)|(?=\})|(?=\])|$)</string>
                            <key>endCaptures</key>
                            <dict>
                              <key>1</key>
                              <dict>
                                <key>name</key>
                                <string>punctuation.end.semicolon.tcl</string>
                              </dict>
                            </dict>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>begin</key>
                                <string>(?:\s+|\\)</string>
                                <key>end</key>
                                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                                <key>endCaptures</key>
                                <dict>
                                  <key>1</key>
                                  <dict>
                                    <key>name</key>
                                    <string>punctuation.end.semicolon.tcl</string>
                                  </dict>
                                </dict>
                                <key>patterns</key>
                                <array>
                                  <dict>
                                    <key>include</key>
                                    <string>#double_quotes</string>
                                  </dict>
                                  <dict>
                                    <key>include</key>
                                    <string>#brackets</string>
                                  </dict>
                                  <dict>
                                    <key>include</key>
                                    <string>#tcl_braces</string>
                                  </dict>
                                </array>
                              </dict>
                            </array>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>while</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.while.tcl</string>
            <key>begin</key>
            <string>\b(while)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.while.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?:\s+|\\)</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#expr_braces</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#brackets</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#tcl_braces</string>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>break</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.break.tcl</string>
            <key>begin</key>
            <string>\b(break)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.break.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:\s+|\\)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>continue</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.continue.tcl</string>
            <key>begin</key>
            <string>\b(continue)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.continue.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:\s+|\\)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>namespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.namespace.tcl</string>
            <key>begin</key>
            <string>\b(namespace)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.namespace.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(eval)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.constant.eval.tcl</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#tcl_braces</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#variable</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#double_quotes</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#brackets</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expr</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.expr.tcl</string>
            <key>begin</key>
            <string>\b(expr)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.expr.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr_braces</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>dict</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.dict.tcl</string>
            <key>begin</key>
            <string>\b(dict)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.dict.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\b(?:for)\b</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.end.semicolon.tcl</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.end.semicolon.tcl</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>endCaptures</key>
                        <dict>
                          <key>1</key>
                          <dict>
                            <key>name</key>
                            <string>punctuation.end.semicolon.tcl</string>
                          </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#variable</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#double_quotes</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#braces</string>
                          </dict>
                          <dict>
                            <key>begin</key>
                            <string>(?:\s+|\\)</string>
                            <key>end</key>
                            <string>(?:(;)|(?=\})|(?=\])|$)</string>
                            <key>endCaptures</key>
                            <dict>
                              <key>1</key>
                              <dict>
                                <key>name</key>
                                <string>punctuation.end.semicolon.tcl</string>
                              </dict>
                            </dict>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>include</key>
                                <string>#double_quotes</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#brackets</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#tcl_braces</string>
                              </dict>
                            </array>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>\b(?:map)\b</string>
                <key>end</key>
                <string>(?:(;)|(?=\})|(?=\])|$)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.end.semicolon.tcl</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>(?:\s+|\\)</string>
                    <key>end</key>
                    <string>(?:(;)|(?=\})|(?=\])|$)</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.end.semicolon.tcl</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#double_quotes</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#braces</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>(?:\s+|\\)</string>
                        <key>end</key>
                        <string>(?:(;)|(?=\})|(?=\])|$)</string>
                        <key>endCaptures</key>
                        <dict>
                          <key>1</key>
                          <dict>
                            <key>name</key>
                            <string>punctuation.end.semicolon.tcl</string>
                          </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#variable</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#double_quotes</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>#braces</string>
                          </dict>
                          <dict>
                            <key>begin</key>
                            <string>(?:\s+|\\)</string>
                            <key>end</key>
                            <string>(?:(;)|(?=\})|(?=\])|$)</string>
                            <key>endCaptures</key>
                            <dict>
                              <key>1</key>
                              <dict>
                                <key>name</key>
                                <string>punctuation.end.semicolon.tcl</string>
                              </dict>
                            </dict>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>include</key>
                                <string>#double_quotes</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#brackets</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#tcl_braces</string>
                              </dict>
                            </array>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#double_quotes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#brackets</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#braces</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>default_command</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:([^\{\}\[\]\$\;\s]+)|(?=\{|\[|\$|\"))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.tcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?:(;)|(?=\})|(?=\])|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.end.semicolon.tcl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#double_quotes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#brackets</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#braces</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tcl_commands</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#proc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#foreach</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#while</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#break</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#continue</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#namespace</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dict</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>