<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
PUBLIC '-//Apple//DTD PLIST 1.0//EN'
'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist>
	<dict>
		<key>fileTypes</key>
		<array>
			<string>tlv</string>
			<string>TLV</string>
		</array>
		<key>foldingStartMarker</key>
		<string>(begin)\s*(//.*)?$</string>
		<key>foldingStopMarker</key>
		<string>^\s*(begin)$</string>
		<key>name</key>
		<string>TL Verilog</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>\b(automatic|cell|config|deassign|defparam|design|disable|edge|endconfig|endgenerate|endspecify|endtable|endtask|event|generate|genvar|ifnone|incdir|instance|liblist|library|localparam|macromodule|negedge|noshowcancelled|posedge|pulsestyle_onevent|pulsestyle_ondetect|real|realtime|scalared|showcancelled|specify|specparam|table|task|time|use|vectored|new)\b</string>
				<key>name</key>
				<string>keyword.other.tlverilog</string>
			</dict>
			<dict>
				<!-- stages: @1, @2, ... -->
				<key>match</key>
				<string>@\b(\d+)\b</string>
				<key>name</key>
				<string>entity.name.stage.tlverilog</string>
			</dict>
			<dict>
				<!-- pipes: |pipe -->
				<key>match</key>
				<string>\|\b([a-zA-Z0-9_]+)\b</string>
				<key>name</key>
				<string>entity.name.pipe.tlverilog</string>
			</dict>
			<dict>
				<!-- tabs: \t -->
				<key>match</key>
				<string>\t</string>
				<key>name</key>
				<string>invalid.illegal.tlverilog</string>
			</dict>
			<dict>
				<!-- Behavioral hierarchy: >start -->
				<key>match</key>
				<string>>([a-zA-Z][a-zA-Z0-9_]+)</string>
				<key>name</key>
				<string>entity.name.hierarchy.tlverilog</string>
			</dict>

			<dict>
				<!-- Behavioral hierarchy: /start -->
				<key>match</key>
				<string>\/([a-zA-Z0-9_]+)</string>
				<key>name</key>
				<string>entity.name.hierarchy.tlverilog</string>
			</dict>

			<dict>
				<!-- When condition: ?$lol | ?*lol -->
				<key>match</key>
				<string>\?[\$\*][a-zA-Z0-9_]+</string>
				<key>name</key>
				<string>keyword.control.conditional.tlverilog</string>
			</dict>

			<dict>
				<!-- System signal: $sig1 -->
				<key>match</key>
				<string>\$\b([a-zA-Z_][a-zA-Z0-9_]+)\b</string>
				<key>name</key>
				<string>variable.other.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>%([+-]\d+|\w+)</string>
				<key>name</key>
				<string>entity.name.alignment.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b([mM]4\+\w+)</string>
				<key>name</key>
				<string>support.macro.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>^\s*\\(TLV.*|SV.*|m4_TLV_version.*)$</string>
				<key>name</key>
				<string>keyword.region.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\*\b([a-zA-Z_][a-zA-Z0-9_]+)\b</string>
				<key>name</key>
				<string>variable.sv.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\#\b([a-zA-Z_][a-zA-Z0-9_]+)\b</string>
				<key>name</key>
				<string>constant.other.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>(&lt;&lt;|&lt;&gt;|&gt;&gt;-?)[a-zA-Z0-9_]+</string>
				<key>name</key>
				<string>entity.name.alignment.tlverilog</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(#|@|begin|end|fork|join|join_any|join_none|forkjoin|{|})\b</string>
				<key>name</key>
				<string>keyword.other.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(initial|always|wait|force|release|assign|always_comb|always_ff|always_latch|forever|repeat|while|for|if|iff|else|case|casex|casez|default|endcase|return|break|continue|do|foreach|randomize|with|inside|dist|clocking|cover|coverpoint|property|bins|binsof|illegal_bins|ignore_bins|randcase|modport|matches|solve|static|assert|assume|before|expect|bind|extends|sequence|var|cross|ref|first_match|srandom|time|struct|packed|final|chandle|alias|tagged|extern|throughout|timeprecision|timeunit|priority|type|union|unique|uwire|wait_order|triggered|randsequence|import|export|context|pure|intersect|wildcard|within|virtual|local|const|typedef|enum|protected|this|super|endmodule|endfunction|endprimitive|endclass|endpackage|endsequence|endprogram|endclocking|endproperty|endgroup|endinterface)\b</string>
				<key>name</key>
				<string>keyword.control.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(std)\b::</string>
				<key>name</key>
				<string>support.class.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\.(atob|atohex|atoi|atooct|atoreal|bintoa|hextoa|itoa|octtoa|realtoa|len|getc|putc|toupper|tolower|compare|icompare|substr|num|exists|first|last|name|index|find|find_first|find_last|find_index|find_first_index|find_last_index|min|max|unique|unique_index|sort|rsort|shuffle|reverse|sum|product|xor|status|kill|self|await|suspend|resume|get|put|peek|try_get|try_peek|try_put|data|eq|neq|next|prev|new|size|delete|empty|pop_front|pop_back|front|back|insert|insert_range|erase|erase_range|set|swap|clear|purge|start|finish)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(get_randstate|set_randstate)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(null|void)\b</string>
				<key>name</key>
				<string>support.constant.tlverilog</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.tlverilog</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.include.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(`include)\s+(["&lt;].*["&gt;])</string>
				<key>name</key>
				<string>meta.include.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>`(celldefine|default_nettype|define|else|elsif|endcelldefine|endif|ifdef|ifndef|include|line|nounconnected_drive|resetall|timescale|unconnected_drive|undef|begin_\w+|end_\w+|remove_\w+|restore_\w+)\b</string>
				<key>name</key>
				<string>constant.other.preprocessor.tlverilog</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>`\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>constant.other.define.tlverilog</string>
			</dict>-->
			<dict>
				<key>include</key>
				<string>#comments</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.tlverilog</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.class.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>\b(function)\b\s+(\[.*\])?\s+\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>meta.definition.tlverilog</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.tlverilog</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.class.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(module|function|primitive|class|package|constraint|interface|covergroup|program)\s+\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>meta.definition.tlverilog</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#all-types</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>(==|===|!=|!==|&lt;=|&gt;=|&lt;|&gt;)</string>
				<key>name</key>
				<string>keyword.operator.comparison.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\-|\+|\*|\/|%)</string>
				<key>name</key>
				<string>keyword.operator.arithmetic.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(!|&amp;&amp;|\|\||\bor\b)</string>
				<key>name</key>
				<string>keyword.operator.logical.tlverilog</string>
			</dict>-->
			<!--<dict>
				<key>match</key>
				<string>(&amp;|\||\^|~|{|}|&lt;&lt;|&gt;&gt;|\?|:)</string>
				<key>name</key>
				<string>keyword.operator.bitwise.tlverilog</string>
			</dict>-->
			<dict>
				<key>match</key>
				<string>'\s*\(.+\)</string>
				<key>name</key>
				<string>keyword.operator.staticcasting.tlverilog</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>'{</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.unpackaedarrayassignment.begin.tlverilog</string>
					</dict>
				</dict>
				<key>end</key>
				<string>}</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.unpackaedarrayassignment.end.tlverilog</string>
					</dict>
				</dict>
				<key>name</key>
				<string>keyword.operator.unpackedarrayassignment.tlverilog</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>.</string>
						<key>name</key>
						<string>constant.character.escape.tlverilog</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(output|input|inout|and|nand|nor|or|xor|xnor|buf|not|bufif[01]|notif[01]|r?[npc]mos|tran|r?tranif[01]|pullup|pulldown)\b</string>
				<key>name</key>
				<string>support.type.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\b\d+)?'[sS]?([bB]\s*[0-1_xXzZ?]+|[oO]\s*[0-7_xXzZ?]+|[dD]\s*[0-9_xXzZ?]+|[hH]\s*[0-9a-fA-F_xXzZ?]+|[0-1xz])((e|E)(\+|-)?[0-9]+)?\b</string>
				<key>name</key>
				<string>constant.numeric.tlverilog</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#strings</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>\$\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>-->
			<!--<dict>
				<key>match</key>
				<string>\b([A-Z][A-Z0-9_]+)\b</string>
				<key>name</key>
				<string>constant.other.tlverilog</string>
			</dict>-->
		</array>
		<key>repository</key>
		<dict>
			<key>all-types</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#storage-type-tlverilog</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#storage-modifier-tlverilog</string>
					</dict>
				</array>
			</dict>
			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>/\*</string>
						<key>captures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\*/</string>
						<key>name</key>
						<string>comment.block.tlverilog</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.tlverilog</string>
							</dict>
						</dict>
						<key>match</key>
						<string>(//).*$\n?</string>
						<key>name</key>
						<string>comment.line.double-slash.tlverilog</string>
					</dict>
				</array>
			</dict>
			<key>storage-type-tlverilog</key>
			<dict>
				<key>match</key>
				<string>\b(wire|tri|tri[01]|supply[01]|wand|triand|wor|trior|trireg|reg|parameter|integer|rand|randc|int|longint|shortint|logic|bit|byte|shortreal|string)\b</string>
				<key>name</key>
				<string>storage.type.tlverilog</string>
			</dict>
			<key>storage-modifier-tlverilog</key>
			<dict>
				<key>match</key>
				<string>\b(signed|unsigned|small|medium|large|supply[01]|strong[01]|pull[01]|weak[01]|highz[01])\b</string>
				<key>name</key>
				<string>storage.modifier.tlverilog</string>
			</dict>
			<key>strings</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>"</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>"</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.tlverilog</string>
							</dict>
						</dict>
						<key>name</key>
						<string>string.quoted.double.tlverilog</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\\.</string>
								<key>name</key>
								<string>constant.character.escape.tlverilog</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>'</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>'</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.tlverilog</string>
							</dict>
						</dict>
						<key>name</key>
						<string>string.quoted.single.tlverilog</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\\.</string>
								<key>name</key>
								<string>constant.character.escape.tlverilog</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.tlverilog</string>
		<key>uuid</key>
		<string>789be04c-8b74-352e-8f37-63d336001277</string>
	</dict>
</plist>
