<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>v</string>
		<string>vh</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~V</string>
	<key>name</key>
	<string>Verilog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#module_pattern</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.verilog</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.verilog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.c-style.verilog</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9]+'[bBoOdDhH][a-fA-F0-9_xXzZ]+\b</string>
					<key>name</key>
					<string>constant.numeric.sized_integer.verilog</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.verilog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.verilog</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.verilog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\d+)(:)(\d+)\b</string>
					<key>name</key>
					<string>meta.block.numeric.range.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+(?i:e\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.integer.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\.\d+(?i:e\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.real.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\d+</string>
					<key>name</key>
					<string>constant.numeric.delay.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[01xXzZ]+\b</string>
					<key>name</key>
					<string>constant.numeric.logic.verilog</string>
				</dict>
			</array>
		</dict>
		<key>instantiation_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*([a-zA-Z][a-zA-Z0-9_]*)\s+([a-zA-Z][a-zA-Z0-9_]*)(?&lt;!begin|if)\s*(?=\(|$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.module.reference.verilog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.module.identifier.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.expression.verilog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.instantiation.parameterless.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*([a-zA-Z][a-zA-Z0-9_]*)\s*(#)(?=\s*\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.module.reference.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.expression.verilog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.instantiation.with.parameters.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parenthetical_list</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z][a-zA-Z0-9_]*</string>
							<key>name</key>
							<string>entity.name.tag.module.identifier.verilog</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(always|and|assign|attribute|begin|buf|bufif0|bufif1|case(xz)?|cmos|deassign|default|defparam|disable|edge|else|end(attribute|case|function|generate|module|primitive|specify|table|task)?|event|for|force|forever|fork|function|generate|genvar|highz(01)|if(none)?|initial|inout|input|integer|join|localparam|medium|module|large|macromodule|nand|negedge|nmos|nor|not|notif(01)|or|output|parameter|pmos|posedge|primitive|pull0|pull1|pulldown|pullup|rcmos|real|realtime|reg|release|repeat|rnmos|rpmos|rtran|rtranif(01)|scalared|signed|small|specify|specparam|strength|strong0|strong1|supply0|supply1|table|task|time|tran|tranif(01)|tri(01)?|tri(and|or|reg)|unsigned|vectored|wait|wand|weak(01)|while|wire|wor|xnor|xor)\b</string>
					<key>name</key>
					<string>keyword.other.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*`((cell)?define|default_(decay_time|nettype|trireg_strength)|delay_mode_(path|unit|zero)|ifdef|include|end(if|celldefine)|else|(no)?unconnected_drive|resetall|timescale|undef)\b</string>
					<key>name</key>
					<string>keyword.other.compiler.directive.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(f(open|close)|readmem(b|h)|timeformat|printtimescale|stop|finish|(s|real)?time|realtobits|bitstoreal|rtoi|itor|(f)?(display|write(h|b)))\b</string>
					<key>name</key>
					<string>support.function.system.console.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(random|dist_(chi_square|erlang|exponential|normal|poisson|t|uniform))\b</string>
					<key>name</key>
					<string>support.function.system.random_number.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$((a)?sync\$((n)?and|(n)or)\$(array|plane))\b</string>
					<key>name</key>
					<string>support.function.system.pld_modeling.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(q_(initialize|add|remove|full|exam))\b</string>
					<key>name</key>
					<string>support.function.system.stochastic.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(hold|nochange|period|recovery|setup(hold)?|skew|width)\b</string>
					<key>name</key>
					<string>support.function.system.timing.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(dump(file|vars|off|on|all|limit|flush))\b</string>
					<key>name</key>
					<string>support.function.system.vcd.tasks.verilog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(countdrivers|list|input|scope|showscopes|(no)?(key|log)|reset(_count|_value)?|(inc)?save|restart|showvars|getpattern|sreadmem(b|h)|scale)</string>
					<key>name</key>
					<string>support.function.non-standard.tasks.verilog</string>
				</dict>
			</array>
		</dict>
		<key>module_pattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(module)\s+([a-zA-Z][a-zA-Z0-9_]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.module.verilog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.module.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\bendmodule\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.module.verilog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.module.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#instantiation_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\+|-|\*|/|%|(&lt;|&gt;)=?|(!|=)?==?|!|&amp;&amp;?|\|\|?|\^?~|~\^?</string>
					<key>name</key>
					<string>keyword.operator.verilog</string>
				</dict>
			</array>
		</dict>
		<key>parenthetical_list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.list.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.list.verilog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.parenthetical_list.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parenthetical_list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.verilog</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.verilog</string>
	<key>uuid</key>
	<string>7F4396B3-A33E-44F0-8502-98CA6C25971F</string>
</dict>
</plist>