general:
    title: General
    description: ""
    type: "none"
    logging:
        description: "Enable show TerosHDL console with each message."
        type: checkbox
    pypath:
        description: "Python3 binary path (e.g.: /usr/bin/python3). Empty if you want to use the system path. <strong>Install teroshdl. E.g: pip3 install teroshdl</strong>"
        type: input
        default: ""
    select_tool:
        description: "Select a tool, framework, simulator..."
        type: select_tool
    waveform_viewer:
        description: "Select the waveform viewer. For GTKWave you need to install it."
        type: select
        options:
            tool: "Tool GUI"
            vcdrom: "VCDrom"
            gtkwave: "GTKWave"
    go_to_definition_vhdl:
        description: "Activate go to definition feature for VHDL (you need to restart VSCode)."
        type: checkbox
    go_to_definition_verilog:
        description: "Activate go to definition feature for Verilog/SV (you need to restart VSCode)."
        type: checkbox
    developer_mode:
        description: "Developer mode: be careful!!"
        type: checkbox

editor:
    title: Editor
    description: ""
    type: "none"
    continue_comment:
        description: "An enter keypress at the end of a line that contains a non-empty comment will continue the comment on the next line. This can be cancelled by pressing enter again. You must also set <code>\"editor.formatOnType\": true\"</code>"
        type: checkbox
        default: false

templates:
    title: Templates
    description: ""
    type: "none"
    header_file_path:
        description: "File path with your configurable header. E.g. your company license. It will be inserted at the beginning of the template"
        type: input
        default: ""

schematic:
    title: Schematic viewer
    description: ""
    type: "none"
    backend:
        description: "Select the backend:"
        type: select
        options:
            yowasp: "YoWASP"
            yosys: "Yosys"
            yosys_ghdl: "GHDL + Yosys"

documentation:
    title: Documentation settings
    description: ""
    type: "none"
    language:
        description: "Documentation language:"
        type: select
        options:
            english: "English"
            russian: "Russian"
    symbol_vhdl:
        description: "Special VHDL symbol at the begin of the comment to extract documentation. Example: <code>--! Code comment</code>"
        type: input
        default: ""
    symbol_verilog:
        description: "Special Verilog symbol at the begin of the comment to extract documentation. Example: <code>//! Code comment</code>"
        type: input
        default: ""
    dependency_graph:
        description: "Include dependency graph:"
        type: checkbox
        default: true
    self_contained:
        description: "HTML documentation self contained:"
        type: checkbox
        default: true
    fsm:
        description: "Include FSM:"
        type: checkbox
        default: true
    signals:
        description: "Include signals:"
        type: select
        options:
            all: "All"
            only_commented: "Only commented"
            none: "None"
    constants:
        description: "Include consants and types:"
        type: select
        options: 
            all: "All"
            only_commented: "Only commented"
            none: "None"
    process:
        description: "Include always/processes:"
        type: select
        options: 
            all: "All"
            only_commented: "Only commented"
            none: "None"
    functions:
        description: "Include functions:"
        type: select
        options:
            all: "All"
            only_commented: "Only commented"
            none: "None"
    magic_config_path:
        description: "Magic config file path"
        type: input
            
linter:
    title: Linters settings
    description: ""
    type: "none"
    linter_vhdl:
        description: "VHDL linter: disable VHDL-LS needs restart VSCode."
        type: select
        options:
            disabled: "Disabled"
            ghdl: "GHDL"
            modelsim: "Modelsim"
            xvhdl: "Vivado (xvhdl)"
            none: "VHDL-LS"
    linter_verilog:
        description: "Verilog/SV linter:"
        type: select
        options:
            disabled: "Disabled"
            icarus: "Icarus"
            modelsim: "Modelsim"
            verilator: "Verilator"
            xvlog: "Vivado (xvlog)"
    style_verilog:
        description: "Verilog/SV style checker:"
        type: select
        options:
            verible: "Verible"
            disabled: "Disabled"
    style_vhdl:
        description: "VHDL style checker:"
        type: select
        options:
            vsg: "VSG"
            disabled: "Disabled"

formatter:
    title: Formatter settings
    description: ""
    type: "none"


    formatter_verilog:
        description: "Verilog/SV formatter:"
        type: select
        options:
            istyle: "iStyle"
            s3sv: "s3sv"
            verible: "Verible"
    formatter_vhdl:
        description: "VHDL formatter:"
        type: select
        options:
            standalone: "Standalone"
            vsg: "VSG"

    subtitle_0:
        type: subtitle
        title: "Verilog/SV iStyle formatter"
    istyle_style:
        description: "Predefined Styling options."
        type: select
        options:
            ansi: "ANSI"
            kernighan&ritchie: "Kernighan&Ritchie"
            gnu: "GNU"
            indent_only: "Indent only"
    istyle_indentation_size:
        description: "Indentation size in number of characters."
        type: input

    subtitle_1:
        type: subtitle
        title: "Verilog/SV S3SV formatter"      
    s3sv_one_bind_per_line:
        description: "Force one binding per line in instanciations statements."
        type: checkbox
    s3sv_one_declaration_per_line:
        description: "Force one declaration per line."
        type: checkbox
    s3sv_use_tabs:
        description: "Use tabs instead of spaces for indentation."
        type: checkbox
    s3sv_indentation_size:
        description: "Indentation size in number of characters."
        type: input

    subtitle_2:
        type: subtitle
        title: "Verilog/SV Verible formatter"      
    verible_path:
        description: "Verible formatter binary path. E.g: /home/user/Downloads/verible-v0.0-1296/bin/verible-verilog-format"
        type: input
    verible_format_args:
        description: "Extra command line arguments passed to the Verible tool"
        type: input_comma

    subtitle_3:
        type: subtitle
        title: "VHDL standalone formatter"      
    vhdl_standalone_keyword_case:
        description: "Keyword case."
        type: select
        options:
            lowercase: "LowerCase"
            uppercase: "UpperCase"
    vhdl_standalone_name_case:
        description: "Type name case."
        type: select
        options:
            lowercase: "LowerCase"
            uppercase: "UpperCase"
    vhdl_standalone_align_comments:
        description: "Align comments."
        type: checkbox
    vhdl_standalone_indentation:
        description: "Indentation."
        type: input
    vhdl_standalone_align_generic_port:
        description: "Align signs in generics and ports."
        type: checkbox

vsg:
    title: VSG
    description: "VHDL Style Guide. Analyzes VHDL files for style guide violations. Reference documentation is located at: <a href=\"https://terostechnology.github.io/terosHDLdoc/style/configuration.html#vsg-vhdl-style-guide\">https://terostechnology.github.io/terosHDLdoc/style/configuration.html#vsg-vhdl-style-guide</a>"
    type: "none"

    configuration:
        description: "JSON or YAML configuration file."
        type: input
