backend:
  description: "Select the backend:"
  type: select
  options:
    yowasp: "YoWASP (Only Verilog/SV)"
    yosys: "Yosys (Only Verilog/SV)"
    yosys_ghdl: "GHDL + Yosys (VHDL+Verilog/SV)"
    standalone: "Standalone (Verilog/SV)"
  value: "yowasp"

extra:
  description: "Extra options passed before to run yowasp-yosys or yosys. Eg: 'conda activate base & ' or 'C:/OSS-CAD-SUITE/oss-cad-suite/start.bat & '" 
  type: string
  value: ""

args:
  description: "Arguments passed to Yosys"
  type: string
  value: ""

args_ghdl:
  description: "Arguments passed to GHDL"
  type: string
  value: ""