name: Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: |
          npm install
          npm run lint

  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          npm install
          npm test

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            test-report/test-report.html

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          fail_below_min: true
          thresholds: '45 60'
          indicators: true

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run UI Tests (ExTester)
        run: |
          npm install
          xvfb-run -a npm run test:ui
