name: Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: |
          npm install
          npm run lint

  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          npm install
          npm test

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            test-report/test-report.html
      
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          fail_below_min: true
          thresholds: '45 60'
          indicators: true
